/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlbumsSlugRouteImport } from './routes/albums.$slug'
import { Route as AlbumsSlugFilenameRouteImport } from './routes/albums.$slug_.$filename'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsSlugRoute = AlbumsSlugRouteImport.update({
  id: '/albums/$slug',
  path: '/albums/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsSlugFilenameRoute = AlbumsSlugFilenameRouteImport.update({
  id: '/albums/$slug_/$filename',
  path: '/albums/$slug/$filename',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/albums/$slug': typeof AlbumsSlugRoute
  '/albums/$slug/$filename': typeof AlbumsSlugFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/albums/$slug': typeof AlbumsSlugRoute
  '/albums/$slug/$filename': typeof AlbumsSlugFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/albums/$slug': typeof AlbumsSlugRoute
  '/albums/$slug_/$filename': typeof AlbumsSlugFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/privacy' | '/albums/$slug' | '/albums/$slug/$filename'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/privacy' | '/albums/$slug' | '/albums/$slug/$filename'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/albums/$slug'
    | '/albums/$slug_/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  AlbumsSlugRoute: typeof AlbumsSlugRoute
  AlbumsSlugFilenameRoute: typeof AlbumsSlugFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$slug': {
      id: '/albums/$slug'
      path: '/albums/$slug'
      fullPath: '/albums/$slug'
      preLoaderRoute: typeof AlbumsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$slug_/$filename': {
      id: '/albums/$slug_/$filename'
      path: '/albums/$slug/$filename'
      fullPath: '/albums/$slug/$filename'
      preLoaderRoute: typeof AlbumsSlugFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  AlbumsSlugRoute: AlbumsSlugRoute,
  AlbumsSlugFilenameRoute: AlbumsSlugFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
